### PR TITLE
Require typing_extensions

### PR DESCRIPTION
**Pull request by gadomski**
`typing_extensions` is required on import here: https://github.com/stac-utils/stac-geoparquet/blob/e13f237be2aa341ceb21abb341fc47d8fe3efeda/stac_geoparquet/arrow/_batch.py#L15

To demonstrate (without this PR):

```shell
$ uv venv && source .venv/bin/activate && uv pip install .
$ python -c "import stac_geoparquet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gadomski/Code/stac-geoparquet/stac_geoparquet/__init__.py", line 3, in <module>
    from . import arrow
  File "/Users/gadomski/Code/stac-geoparquet/stac_geoparquet/arrow/__init__.py", line 1, in <module>
    from ._api import (
  File "/Users/gadomski/Code/stac-geoparquet/stac_geoparquet/arrow/_api.py", line 9, in <module>
    from stac_geoparquet.arrow._batch import StacArrowBatch, StacJsonBatch
  File "/Users/gadomski/Code/stac-geoparquet/stac_geoparquet/arrow/_batch.py", line 15, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
```

Closes https://github.com/stac-utils/stac-geoparquet/issues/68

### CODE REVIEW

**Comment by kylebarron** [comment]
Indeed, thanks, I missed that. Should we conditionally require typing_extensions only pre Python 3.11? I think `Self` was introduced then?

**Comment by gadomski** [comment]
> Should we conditionally require typing_extensions only pre Python 3.11? I think Self was introduced then?

Sure, but we'd need to conditionally switch the import from `typing_extensions` to `typing` for newer versions (e.g. https://github.com/microsoft/pylance-release/issues/2034#issuecomment-1207076000).

**Comment by TomAugspurger** [comment]
I just wrote up https://github.com/stac-utils/stac-geoparquet/issues/68 for that :)

I'm fine with merging this and doing that later (I can get to it this afternoon).

**Comment by kylebarron** [comment]
I updated this to conditionally use typing if on python >= 3.11

**Review by kylebarron — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
