### PR TITLE
Add documentation website

### PR DESCRIPTION
**Pull request by kylebarron**
### Change list

- Set up mkdocs config (derived from lonboard)
- Add `docs` section of dependencies to `pyproject.toml`
- Add `geopandas.md` file linking to docstrings of top-level "legacy" exports. (As an aside: should we actually deprecate any of that code? I'm not sure if the schema from `stac_geoparquet.to_geodataframe` would match what we're constructing from the Arrow side.
- Sphinx-based interlinks in the API docs work with pyarrow, geopandas, and pystac. mkdocstrings is really amazing

### Todo:

- [ ] Flesh out Arrow, GeoParquet, Delta Lake documentation

Some screenshots:

image

image

### CODE REVIEW

**Comment by TomAugspurger** [comment]
> (As an aside: should we actually deprecate any of that code? I'm not sure if the schema from stac_geoparquet.to_geodataframe would match what we're constructing from the Arrow side.

Probably... I have some pipelines that I need to update to use the new arrow stuff. Maybe a deprecation warning would be the motivation I need :)

**Review by gadomski — CHANGES_REQUESTED** [review]
One warning popped up during building that's worth flagging:

```text
WARNING -  Doc file 'index.md' contains a link './spec/stac-geoparquet-spec.md', but the target 'spec/stac-geoparquet-spec.md' is not found among documentation files.
```

I _think_ that means we should symlink the spec into `docs/spec/stac-geoparquet-spec.md`? I haven't used **mkdocs** before so that's a guess.

Also, it'd be good to put a CI check in to build the docs (maybe with warnings turned to errors) to catch any regressions (in addition to the publishing Tom mentioned). I've done a decent amount of Github CI work as well so lmk if you like me to take a crack.

**Comment by kylebarron** [comment]
> Have you built these in CI and automatically published them to gh-pages before? It'd be nice to get that set up, but no worries if it's a hassle.

Yeah Lonboard automatically publishes to CI on a new tag with the format `v*`. I'll add that today

**Comment by kylebarron** [comment]
> Also, it'd be good to put a CI check in to build the docs (maybe with warnings turned to errors) to catch any regressions (in addition to the publishing Tom mentioned).

Done in [`384eb2e` (#65)](https://github.com/stac-utils/stac-geoparquet/pull/65/commits/384eb2e6554e9ebdc21bb8f96377585e2d78448b)

**Comment by kylebarron** [comment]
I think this is good to merge as is, and I'll clean up my draft of the "Usage" and "Schema considerations" pages on Monday

**Review by TomAugspurger — APPROVED** [review]
Thanks!

**Pull request merged**
